
OrdererOrgs:
  - Name: Orderer
    Domain: atguigu.com
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Org1
    Domain: org1.atguigu.com
    Template:
      Count: 1
    Users:
      Count: 1
