const path = require('path');
const Web3 = require('web3');// Note: web3 1.0.0

//Note:IP is determined by the dev-test environment
const web3 = new Web3(new Web3.providers.HttpProvider("http://localhost:8545"));
const filePath = path.resolve(__dirname, '../compiled/', 'Car.json');
//Note: ‘interface’ and ‘bytecode’ cannot be modified. Generated by the compiled file.
const { interface, bytecode } = require(filePath);

const abi = JSON.parse(interface);
const contract = web3.eth.contract(abi);
const _from = web3.eth.accounts[0];
const txObj = {data:bytecode,from:_from,gas:5000000};

let contractInstance = contract.new(txObj,(err,res)=>{
    if (err)
        console.log("Error:",err);
    else 
        console.log("Result:",res);
        console.log("Successful contract deployment:",res.address);
})

